apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ .Release.Name }}

spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: {{ .Release.Name }}

  template:
    metadata:
      labels:
        app: {{ .Release.Name }}

    spec:
      containers:

      - name: train-app

        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"

        ports:
        - containerPort: 8080


        env:
        - name: DB_URL
          value: {{ .Values.env.DB_URL | quote }}

        - name: DB_USER
          value: {{ .Values.env.DB_USER | quote }}

        - name: DB_PASS
          value: {{ .Values.env.DB_PASS | quote }}
